import streamlit as st
import math
import pandas as pd
from fpdf import FPDF
import plotly.graph_objects as go
import io
import os

st.set_page_config(page_title="Chiller Plant Room Verification Tool", layout="wide")

# ---------------------------------------------------------------------------
# --- Green Mark Dashboard logic ---
# ---------------------------------------------------------------------------
def greenmark_check(chiller_kw_per_rt, pump_kw_per_rt, approach_c, cycles):
    results = {}
    results["Chiller Efficiency"] = "Pass" if chiller_kw_per_rt <= 0.65 else "Fail"
    results["Pump Efficiency"] = "Pass" if pump_kw_per_rt <= 0.04 else "Fail"
    results["Cooling Tower Approach"] = "Pass" if approach_c <= 3.5 else "Fail"
    results["Cycles of Concentration"] = "Pass" if cycles >= 5 else "Fail"
    return results


def weighted_scoring(results):
    weights = {
        "Chiller Efficiency": 40,
        "Pump Efficiency": 20,
        "Cooling Tower Approach": 20,
        "Cycles of Concentration": 20,
    }
    scores = {}
    for k, v in results.items():
        scores[k] = weights[k] if v == "Pass" else 0
    total = sum(scores.values())
    return scores, total


def assign_greenmark_rating(total_score):
    if total_score >= 95:
        return "Super Low Energy (SLE)"
    elif total_score >= 90:
        return "Platinum"
    elif total_score >= 75:
        return "GoldPLUS"
    elif total_score >= 60:
        return "Gold"
    else:
        return "Certified"


# ---------------------------------------------------------------------------
# --- PDF Export ---
# ---------------------------------------------------------------------------
def generate_pdf_report(results, scores, total_score, rating,
                         company_name="Jayros Technologies Inc.", logo_path="logo.png"):
    pdf = FPDF()
    pdf.add_page()

    # Logo (optional, silently skipped if missing)
    if logo_path and os.path.exists(logo_path):
        try:
            pdf.image(logo_path, x=10, y=8, w=30)
        except Exception:
            pass

    # Header
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, f"{company_name}", ln=True, align="C")
    pdf.set_font("Arial", "I", 12)
    pdf.cell(200, 10, "Singapore Green Mark Compliance Report", ln=True, align="C")
    pdf.ln(20)

    # Table Header
    pdf.set_font("Arial", "B", 12)
    pdf.cell(100, 10, "Parameter", 1)
    pdf.cell(40, 10, "Status", 1)
    pdf.cell(50, 10, "Score", 1)
    pdf.ln()

    # Table Content
    pdf.set_font("Arial", "", 12)
    for k, v in results.items():
        pdf.cell(100, 10, k, 1)
        pdf.cell(40, 10, v, 1)
        pdf.cell(50, 10, str(scores[k]), 1)
        pdf.ln()

    # Total + Rating
    pdf.ln(10)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(200, 10, f"Total Score: {total_score}/100", ln=True, align="C")
    pdf.cell(200, 10, f"Overall Green Mark Rating: {rating}", ln=True, align="C")

    # Footer
    pdf.set_y(-30)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(200, 10, "Generated by Jayros Technologies Compliance Tool", ln=True, align="C")

    return pdf.output(dest="S").encode("latin-1")


# ---------------------------------------------------------------------------
# --- Supplier datasheet comparison helpers ---
# ---------------------------------------------------------------------------
def load_supplier_file(uploaded_file):
    """Read a single uploaded CSV/Excel file into a DataFrame, tagged with source filename."""
    name = uploaded_file.name
    try:
        if name.lower().endswith(".csv"):
            df = pd.read_csv(uploaded_file)
        else:
            df = pd.read_excel(uploaded_file)
        df["__source_file"] = name
        return df, None
    except Exception as e:
        return None, str(e)


def build_comparison_table(dataframes):
    """Stack supplier dataframes on shared columns for side-by-side comparison."""
    if not dataframes:
        return pd.DataFrame()
    common_cols = set(dataframes[0].columns)
    for df in dataframes[1:]:
        common_cols &= set(df.columns)
    common_cols.discard("__source_file")
    ordered_cols = ["__source_file"] + sorted(common_cols)
    combined = pd.concat([df[ordered_cols] for df in dataframes], ignore_index=True)
    combined = combined.rename(columns={"__source_file": "Source File"})
    return combined


# ---------------------------------------------------------------------------
# --- Streamlit UI ---
# ---------------------------------------------------------------------------
st.title("Chiller Plant Room Verification Tool (Singapore Green Mark)")

tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8, tab9 = st.tabs([
    "Chiller", "Piping", "Pump", "Cooling Tower", "Make-up Water",
    "Expansion Tank", "Green Mark Dashboard", "Export Report", "Supplier Data"
])

with tab1:
    st.header("Chiller Verification")
    cop = st.number_input("Chiller COP", value=5.5, min_value=0.01, step=0.1)
    kw_per_ton = 3.516 / cop
    st.write(f"Chiller Efficiency: {kw_per_ton:.2f} kW/RT")
    st.session_state["kw_per_ton"] = kw_per_ton

with tab2:
    st.header("Piping Verification")
    flow_lps = st.number_input("Flow (L/s)", value=15.0, min_value=0.0, step=0.5)
    pipe_d_mm = st.number_input("Pipe Diameter (mm)", value=150.0, min_value=1.0, step=5.0)
    vel_ms = flow_lps / (math.pi * (pipe_d_mm / 1000 / 2) ** 2) if pipe_d_mm > 0 else 0
    st.write(f"Pipe Velocity: {vel_ms:.2f} m/s")
    st.session_state["flow_lps"] = flow_lps

with tab3:
    st.header("Pump Verification")
    required_head = st.number_input("Required Head (m)", value=12.0)
    required_flow = st.number_input("Required Flow (L/s)", value=15.0)
    pump_head = st.number_input("Supplier Pump Head (m)", value=15.0)
    pump_flow = st.number_input("Supplier Pump Flow (L/s)", value=16.0)
    st.write("✅ Pump meets requirements" if pump_head >= required_head and pump_flow >= required_flow
              else "❌ Pump undersized")

with tab4:
    st.header("Cooling Tower Verification")
    t_hot = st.number_input("Hot Water Temp (°C)", value=35.0)
    t_cold = st.number_input("Cold Water Temp (°C)", value=29.0)
    t_wb = st.number_input("Wet Bulb Temp (°C)", value=26.0)
    approach_val = t_cold - t_wb
    st.write(f"Approach: {approach_val:.1f} °C")
    st.session_state["approach_val"] = approach_val

with tab5:
    st.header("Make-up Water & Tank")
    flow_for_makeup = st.session_state.get("flow_lps", flow_lps)
    total = flow_for_makeup * (0.0015 + 0.001 + 0.015)
    tank_volume = total * 3600 * 24 * 1.5
    st.write(f"Make-up Water Flow: {total:.3f} L/s")
    st.write(f"Tank Volume: {tank_volume:.1f} L")

with tab6:
    st.header("Expansion Tank / Degassing")
    system_volume = st.number_input("System Volume (m³)", value=50.0)
    delta_t_c = st.number_input("Temperature Rise (°C)", value=10.0)
    expansion_vol = system_volume * delta_t_c * 0.00021
    tank_size = expansion_vol * 1.25
    st.write(f"Expansion Volume: {expansion_vol:.2f} m³")
    st.write(f"Expansion Tank Size: {tank_size:.2f} m³")

with tab7:
    st.header("Singapore Green Mark Dashboard")
    cycles = st.number_input("Cycles of Concentration", value=5, min_value=1, step=1)

    kw_per_ton = st.session_state.get("kw_per_ton", kw_per_ton)
    approach_val = st.session_state.get("approach_val", approach_val)

    gm_results = greenmark_check(kw_per_ton, 0.03, approach_val, cycles)
    scores, total_score = weighted_scoring(gm_results)
    rating = assign_greenmark_rating(total_score)

    for k, v in gm_results.items():
        color = "green" if v == "Pass" else "red"
        st.markdown(f"**{k}:** <span style='color:{color}'>{v}</span> — Score: {scores[k]}",
                    unsafe_allow_html=True)

    st.markdown(f"### Total Score: **{total_score}/100**")
    st.markdown(f"### Overall Rating: **{rating}**")

    # Gauge visualization
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=total_score,
        title={"text": "Green Mark Score"},
        gauge={
            "axis": {"range": [0, 100]},
            "bar": {"color": "darkblue"},
            "steps": [
                {"range": [0, 60], "color": "red"},
                {"range": [60, 75], "color": "orange"},
                {"range": [75, 90], "color": "yellow"},
                {"range": [90, 95], "color": "green"},
                {"range": [95, 100], "color": "purple"},  # Super Low Energy
            ],
        },
    ))
    st.plotly_chart(fig, use_container_width=True)

    # Persist for the Export tab
    st.session_state["gm_results"] = gm_results
    st.session_state["scores"] = scores
    st.session_state["total_score"] = total_score
    st.session_state["rating"] = rating

with tab8:
    st.header("Export Compliance Report")

    if "gm_results" not in st.session_state:
        st.warning("Please visit the **Green Mark Dashboard** tab first to generate results.")
    else:
        company_name = st.text_input("Company Name", value="Jayros Technologies Inc.")
        logo_file = st.file_uploader("Optional: Upload company logo (PNG/JPG)", type=["png", "jpg", "jpeg"])

        logo_path = None
        if logo_file is not None:
            logo_path = f"/tmp/{logo_file.name}"
            with open(logo_path, "wb") as f:
                f.write(logo_file.getbuffer())

        pdf_bytes = generate_pdf_report(
            st.session_state["gm_results"],
            st.session_state["scores"],
            st.session_state["total_score"],
            st.session_state["rating"],
            company_name=company_name,
            logo_path=logo_path,
        )
        st.download_button("Download Report (PDF)", pdf_bytes, "GreenMark_Report.pdf", "application/pdf")

with tab9:
    st.header("Supplier Technical Data Comparison")
    uploaded_files = st.file_uploader(
        "Upload Supplier Datasheets (Excel/CSV)",
        type=["xls", "xlsx", "csv"],
        accept_multiple_files=True,
    )

    if uploaded_files:
        dataframes = []
        for f in uploaded_files:
            df, err = load_supplier_file(f)
            if err:
                st.error(f"Could not read **{f.name}**: {err}")
                continue
            dataframes.append(df)
            with st.expander(f"Preview: {f.name}"):
                st.dataframe(df.drop(columns=["__source_file"], errors="ignore"))

        if dataframes:
            st.subheader("Side-by-Side Comparison")
            comparison_df = build_comparison_table(dataframes)

            if comparison_df.empty or comparison_df.shape[1] <= 1:
                st.info(
                    "No common columns were found across the uploaded files, so a merged "
                    "comparison table couldn't be built. Review the individual previews above instead."
                )
            else:
                st.dataframe(comparison_df, use_container_width=True)

                # Highlight best (numeric) values per shared column, where lower is typically better
                numeric_cols = comparison_df.select_dtypes(include="number").columns
                if len(numeric_cols) > 0:
                    st.subheader("Lowest Value per Numeric Column (per supplier row)")
                    best_rows = {}
                    for col in numeric_cols:
                        idx = comparison_df[col].idxmin()
                        best_rows[col] = comparison_df.loc[idx, "Source File"]
                    best_df = pd.DataFrame(
                        {"Column": list(best_rows.keys()), "Best (Lowest) Source File": list(best_rows.values())}
                    )
                    st.dataframe(best_df, use_container_width=True)

                csv_buffer = io.StringIO()
                comparison_df.to_csv(csv_buffer, index=False)
                st.download_button(
                    "Download Comparison Table (CSV)",
                    csv_buffer.getvalue(),
                    "supplier_comparison.csv",
                    "text/csv",
                )
    else:
        st.info("Upload two or more supplier datasheets (CSV or Excel) to compare them side by side.")
